apiVersion: skaffold/v1
kind: Config
build:                                     
  tagPolicy:
    sha256: {}
  local: 
    push: true    # On s’authorise a pusher sur notre repository local
  insecureRegistries:
  - k3d-myregistry.localhost:5000          
  artifacts:
     # docker build -t k3d-myregistry.localhost:5000/nodejs-guestbook-frontend:<complex_tag> src/frontend
     # docker push k3d-myregistry.localhost:5000/nodejs-guestbook-frontend:<complex_tag>                          
  - image: k3d-myregistry.localhost:5000/nodejs-guestbook-frontend       
    context: src/frontend
     # docker build -t k3d-myregistry.localhost:5000/nodejs-guestbook-backend:<complex_tag> src/backend
     # docker push k3d-myregistry.localhost:5000/nodejs-guestbook-backend:<complex_tag>  
  - image: k3d-myregistry.localhost:5000/nodejs-guestbook-backend       
    context: src/backend
deploy:                                    # Pour déployer dans le cluster
 kustomize:                                # kubectl/helm ou kustomize
   path: "kustomize/overlays/dev"          # kubectl apply -k kustomize/overlays/dev
#kubectl:
#   manifests:
#    - k8s/*
#helm:
#  helm:
#    releases:
#    - name: guestbook
#      chartPath: helm/guestbook
#      valuesFiles: helm/devValues.yaml


portForward:
- resourceType: deployment
  resourceName: nodejs-guestbook-frontend
  port: 8080
  localPort: 8000