
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
 name: guestbook
 annotations:
   ingress.kubernetes.io/ssl-redirect: "false"
spec:
 rules:
 - host: {{ .Values.ingressHost }}
   http:
     paths:
     - path: /
       backend:
         serviceName: nodejs-guestbook-frontend
         servicePort: 80
